### ISSUE TITLE
DLC and localization fixes

### ISSUE THREAD

**Issue by molsen234** [davkas88/ModNotIncluded#2]
Hello Davkas88,

I saw on Steam that you don't have much time for modding these days. Since so many people enjoy your mods, I updated them to fully support DLC, and I replaced the localization method to use .po files as in the game (migrated the translations you already have).

Unfortunately that is a rather large change to the code, so I am not going to just do a PR without your approval. I forked, and you can check out the changes I made and let me know if you are interested in publishing it on Steam or if the changes are too large. After all, it is your mod, not mine. Functionally it does exactly the same, but I rearranged the files to get the DLC/vanilla stuff all in one place per mod.

https://github.com/molsen234/ModNotIncluded

There is a change_notes.txt file in root that explains the things I changed.

Thanks for having made these wonderful mods!

Many kind regards,
Michael

**Comment by davkas88** [comment]
ok thanks, i try the update, if all works, i can add you ass collaborator on workshop page

**Comment by davkas88** [comment]
ok I did some quick tests and everything seems ok, I update the mod on the workshop, and I will update all the code also on this page, you will be mentioned in the mods page, and if you want I can add you as a collaborator.

**Comment by molsen234** [comment]
That was fast! I'm sure it makes a lot of people happy :) You don't have to add me as collaborator, I am not on Steam that often. Thanks once more for the mods, they are some of my favorite ones!
